repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.2
    hooks:
      - id: clang-format
        name: clang-format
        files: \.(cpp|hpp|c|h)$

  - repo: local
    hooks:
      - id: c-lint
        name: c-lint
        entry: clang-tidy
        language: system
        files: \.(c|h|cc)$
        args:
          - -p
          - ../../build/PackageName/ # Replace 'build/' with your actual compilation database path (add set(CMAKE_EXPORT_COMPILE_COMMANDS ON) in CMakeLists.txt)
          - -extra-arg=-isystem
          - -extra-arg=../../install/include # Replace 'install/include' with your actual system include path

      - id: cpp-lint
        name: cpp-lint
        entry: clang-tidy
        language: system
        files: \.(cpp|hpp)$
        args:
          - -p
          - ../../build/PackageName/ # Replace 'build/' with your actual compilation database path (add set(CMAKE_EXPORT_COMPILE_COMMANDS ON) in CMakeLists.txt)
          - -extra-arg=-isystem
          - -extra-arg=../../install/include # Replace 'install/include' with your actual system include path

      - id: cmake-format
        name: cmake-format
        entry: cmake-format
        language: python
        types: [cmake]
        args: [--in-place]

      - id: cmake-lint
        name: cmake-lint
        entry: cmake-lint
        language: python
        types: [cmake]

  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
        args: [-conf, .yamlfmt.yaml]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [--fix]
